// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SapLoVcSharp.Data.Sqlite;

#nullable disable

namespace SapLoVcSharp.Data.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20251121080551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DependencyExecutionLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsistent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisplayOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMultiValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestrictable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassName", "Name");

                    b.HasIndex("Name");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassName", "CharacteristicName", "Value");

                    b.HasIndex("Value");

                    b.ToTable("CharacteristicValues");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ClassEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("ClassType");

                    b.HasIndex("Status");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialNumber")
                        .IsUnique();

                    b.ToTable("ConfigurationProfiles");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileProcedureEntity", b =>
                {
                    b.Property<string>("ConfigurationProfileId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigurationProfileId", "DependencyId");

                    b.HasIndex("ConfigurationProfileId");

                    b.HasIndex("DependencyId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("ConfigurationProfileProcedures");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AstJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetConstraintEntity", b =>
                {
                    b.Property<string>("DependencyNetId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("DependencyNetId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.HasIndex("DependencyNetId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("DependencyNetConstraints");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationProfileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationProfileId");

                    b.HasIndex("Status");

                    b.ToTable("DependencyNets");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialClassAssignmentEntity", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNumber", "ClassName");

                    b.HasIndex("ClassName");

                    b.ToTable("MaterialClassAssignments");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialEntity", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNumber");

                    b.HasIndex("MaterialType");

                    b.HasIndex("Status");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ValueDependencyEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClassName", "CharacteristicName", "CharacteristicValue", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("ValueDependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ClassEntity", "Class")
                        .WithMany("Characteristics")
                        .HasForeignKey("ClassName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.CharacteristicEntity", "Characteristic")
                        .WithMany("Values")
                        .HasForeignKey("ClassName", "CharacteristicName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.MaterialEntity", "Material")
                        .WithOne("ConfigurationProfile")
                        .HasForeignKey("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "MaterialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileProcedureEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "ConfigurationProfile")
                        .WithMany("Procedures")
                        .HasForeignKey("ConfigurationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationProfile");

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetConstraintEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.DependencyNetEntity", "DependencyNet")
                        .WithMany("Constraints")
                        .HasForeignKey("DependencyNetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("DependencyNet");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "ConfigurationProfile")
                        .WithMany("DependencyNets")
                        .HasForeignKey("ConfigurationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationProfile");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialClassAssignmentEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ClassEntity", "Class")
                        .WithMany("MaterialAssignments")
                        .HasForeignKey("ClassName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.MaterialEntity", "Material")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ValueDependencyEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.CharacteristicValueEntity", "CharacteristicValueEntity")
                        .WithMany("Dependencies")
                        .HasForeignKey("ClassName", "CharacteristicName", "CharacteristicValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicValueEntity");

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ClassEntity", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("MaterialAssignments");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.Navigation("DependencyNets");

                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialEntity", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("ConfigurationProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
