// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SapLoVcSharp.Data.Sqlite;

#nullable disable

namespace SapLoVcSharp.Data.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20251204075954_UpdateProductMatrixSchema")]
    partial class UpdateProductMatrixSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DependencyExecutionLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConsistent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependencyId");

                    b.HasIndex("ExecutedAt");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisplayOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMultiValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestrictable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassName", "Name");

                    b.HasIndex("Name");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClassName", "CharacteristicName", "Value");

                    b.HasIndex("Value");

                    b.ToTable("CharacteristicValues");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ClassEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("ClassType");

                    b.HasIndex("Status");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialNumber")
                        .IsUnique();

                    b.ToTable("ConfigurationProfiles");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileProcedureEntity", b =>
                {
                    b.Property<string>("ConfigurationProfileId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigurationProfileId", "DependencyId");

                    b.HasIndex("ConfigurationProfileId");

                    b.HasIndex("DependencyId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("ConfigurationProfileProcedures");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AstJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetConstraintEntity", b =>
                {
                    b.Property<string>("DependencyNetId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("DependencyNetId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.HasIndex("DependencyNetId");

                    b.HasIndex("SequenceNumber");

                    b.ToTable("DependencyNetConstraints");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationProfileId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationProfileId");

                    b.HasIndex("Status");

                    b.ToTable("DependencyNets");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialClassAssignmentEntity", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNumber", "ClassName");

                    b.HasIndex("ClassName");

                    b.ToTable("MaterialClassAssignments");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialEntity", b =>
                {
                    b.Property<string>("MaterialNumber")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialNumber");

                    b.HasIndex("MaterialType");

                    b.HasIndex("Status");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixCellEntity", b =>
                {
                    b.Property<string>("MatrixName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MatrixName", "SheetIndex", "RowIndex", "ColumnIndex");

                    b.HasIndex("MatrixName", "SheetIndex", "ColumnIndex");

                    b.ToTable("ProductMatrixCells");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixColumnEntity", b =>
                {
                    b.Property<string>("MatrixName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnStyle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupHeader")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultCharacteristicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MatrixName", "SheetIndex", "ColumnIndex");

                    b.ToTable("ProductMatrixColumns");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedVariantTableName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("GeneratedVariantTableName");

                    b.HasIndex("MaterialNumber");

                    b.HasIndex("Status");

                    b.ToTable("ProductMatrices");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixRowEntity", b =>
                {
                    b.Property<string>("MatrixName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RowLabel")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MatrixName", "SheetIndex", "RowIndex");

                    b.ToTable("ProductMatrixRows");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixSheetEntity", b =>
                {
                    b.Property<string>("MatrixName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("MatrixName", "SheetIndex");

                    b.ToTable("ProductMatrixSheets");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ValueDependencyEntity", b =>
                {
                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CharacteristicValue")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ClassName", "CharacteristicName", "CharacteristicValue", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("ValueDependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.VariantTableColumnEntity", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacteristicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKeyColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SqlDataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TableName", "ColumnIndex");

                    b.HasIndex("TableName", "ColumnIndex");

                    b.ToTable("VariantTableColumns");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.VariantTableEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseTableName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTableCreated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("DatabaseTableName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("VariantTables");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ClassEntity", "Class")
                        .WithMany("Characteristics")
                        .HasForeignKey("ClassName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.CharacteristicEntity", "Characteristic")
                        .WithMany("Values")
                        .HasForeignKey("ClassName", "CharacteristicName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.MaterialEntity", "Material")
                        .WithOne("ConfigurationProfile")
                        .HasForeignKey("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "MaterialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileProcedureEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "ConfigurationProfile")
                        .WithMany("Procedures")
                        .HasForeignKey("ConfigurationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationProfile");

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetConstraintEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.DependencyNetEntity", "DependencyNet")
                        .WithMany("Constraints")
                        .HasForeignKey("DependencyNetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependency");

                    b.Navigation("DependencyNet");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", "ConfigurationProfile")
                        .WithMany("DependencyNets")
                        .HasForeignKey("ConfigurationProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationProfile");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialClassAssignmentEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ClassEntity", "Class")
                        .WithMany("MaterialAssignments")
                        .HasForeignKey("ClassName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.MaterialEntity", "Material")
                        .WithMany("ClassAssignments")
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixCellEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ProductMatrixColumnEntity", "Column")
                        .WithMany()
                        .HasForeignKey("MatrixName", "SheetIndex", "ColumnIndex")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.ProductMatrixRowEntity", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("MatrixName", "SheetIndex", "RowIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixColumnEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ProductMatrixSheetEntity", "Sheet")
                        .WithMany("Columns")
                        .HasForeignKey("MatrixName", "SheetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.VariantTableEntity", "GeneratedVariantTable")
                        .WithMany()
                        .HasForeignKey("GeneratedVariantTableName")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SapLoVcSharp.Data.Models.MaterialEntity", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedVariantTable");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixRowEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ProductMatrixSheetEntity", "Sheet")
                        .WithMany("Rows")
                        .HasForeignKey("MatrixName", "SheetIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sheet");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixSheetEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.ProductMatrixEntity", "Matrix")
                        .WithMany("Sheets")
                        .HasForeignKey("MatrixName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ValueDependencyEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.DependencyEntity", "Dependency")
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SapLoVcSharp.Data.Models.CharacteristicValueEntity", "CharacteristicValueEntity")
                        .WithMany("Dependencies")
                        .HasForeignKey("ClassName", "CharacteristicName", "CharacteristicValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicValueEntity");

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.VariantTableColumnEntity", b =>
                {
                    b.HasOne("SapLoVcSharp.Data.Models.VariantTableEntity", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicEntity", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.CharacteristicValueEntity", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ClassEntity", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("MaterialAssignments");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ConfigurationProfileEntity", b =>
                {
                    b.Navigation("DependencyNets");

                    b.Navigation("Procedures");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.DependencyNetEntity", b =>
                {
                    b.Navigation("Constraints");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.MaterialEntity", b =>
                {
                    b.Navigation("ClassAssignments");

                    b.Navigation("ConfigurationProfile");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixEntity", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixRowEntity", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.ProductMatrixSheetEntity", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("SapLoVcSharp.Data.Models.VariantTableEntity", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
